/* ============================================================
   lang.c — UI string translation tables (English / Italian)
   ============================================================ */
#include "lang.h"
#include "globals.h"

static const char *stringsEN[STR_COUNT] = {
    [STR_FOOTER_BACK_EXIT_HELP]       = "B: Back  START: Exit  SELECT: Help",
    [STR_SELECTED_FMT]                = "Selected (%d)",
    [STR_AND_N_MORE_FMT]              = "...and %d more",
    [STR_NO_BACKUP]                   = "No backup",
    [STR_BACKUP_FMT]                  = "Backup: %s",
    [STR_UNKNOWN]                     = "Unknown",
    [STR_TYPE_UPDATE]                 = "Update",
    [STR_TYPE_DLC]                    = "DLC",
    [STR_TYPE_GAME]                   = "Game",
    [STR_SORT_NAME]                   = "Name",
    [STR_SORT_SIZE]                   = "Size",
    [STR_SORT_ID]                     = "ID",
    [STR_TITLE_DETAILS]               = "Title Details",
    [STR_RELEASE_SELECT_RETURN]       = "Release SELECT to return.",
    [STR_A_CONTINUE]                  = "  A=Continue",
    [STR_A_OK]                        = "  A=OK",
    [STR_A_YES_B_NO]                  = "  A=Yes   B=No",
    [STR_LOADING]                     = "Loading...",
    [STR_LOADING_TITLES]              = "Loading titles...",
    [STR_DO_NOT_POWER_OFF]            = "Do not power off the console.",

    [STR_APP_TITLE_FMT]               = "3DS Fast Uninstall  %s",
    [STR_MENU_INSTALL]                = "Install CIA",
    [STR_MENU_BACKUP]                 = "Backup Saves",
    [STR_MENU_UNINSTALL]              = "Uninstall Titles",
    [STR_MENU_SYSINFO]                = "System Info",
    [STR_MENU_SETTINGS]               = "Settings",
    [STR_MENU_FOOTER_TOP]             = "START: Exit  SELECT: Help",
    [STR_MENU_FOOTER_BOTTOM]          = "A: Select  START: Exit  SEL: Help",
    [STR_MENU_DESCRIPTION]            = "Description",
    [STR_MENU_DESC_INSTALL_1]         = "Install .CIA files from the SD card.",
    [STR_MENU_DESC_INSTALL_2]         = "Supports single file and batch install.",
    [STR_MENU_DESC_BACKUP_1]          = "Backup save data for installed titles.",
    [STR_MENU_DESC_BACKUP_2]          = "Backup single title or entire library.",
    [STR_MENU_DESC_UNINSTALL_1]       = "Uninstall titles with optional backup.",
    [STR_MENU_DESC_UNINSTALL_2]       = "Supports batch uninstall with X button.",
    [STR_MENU_DESC_SYSINFO_1]         = "View info on games, updates and DLC.",
    [STR_MENU_DESC_SYSINFO_2]         = "Includes backup, restore and delete.",
    [STR_MENU_DESC_SETTINGS_1]        = "Configure application settings.",

    [STR_UNINSTALL_HEADER]            = "Uninstall",
    [STR_UNINSTALL_INFO_FMT]          = "T:%-3d Sel:%-3d Sort:",
    [STR_FILTER_ALL]                  = "All",
    [STR_FILTER_UPD]                  = "Upd",
    [STR_FILTER_DLC]                  = "DLC",
    [STR_NO_TITLES]                   = "No titles to show.",

    [STR_INSTALL_HEADER]              = "Install CIA",
    [STR_DIR_PREFIX_FMT]              = "[DIR] %s/",
    [STR_FILE_INFO]                   = "File Info",
    [STR_FILE_ID_FMT]                 = "ID: %016llX",
    [STR_FILE_ID_NA]                  = "ID: N/A",
    [STR_FILE_SIZE_FMT]               = "Size: %s",
    [STR_GO_TO_PARENT]                = "Go to parent folder",
    [STR_FOLDER_FMT]                  = "Folder: %.30s",
    [STR_EMPTY_FOLDER]                = "Empty folder",
    [STR_TYPE_UPDATE_BADGE]           = "Type: Update  [^]",
    [STR_TYPE_DLC_BADGE]              = "Type: DLC     [+]",
    [STR_TYPE_GAME_LABEL]             = "Type: Game",

    [STR_BACKUP_HEADER_FMT]           = "Save Backups   Sel:%d",
    [STR_SORT_FMT]                    = "Sort:%s",

    [STR_SYSINFO_HEADER]              = "SYSTEM INFORMATION",
    [STR_SYSINFO_ROW_GAMES]           = "Games:",
    [STR_SYSINFO_ROW_UPDATES]         = "Updates:",
    [STR_SYSINFO_ROW_DLC]             = "DLC:",
    [STR_SYSINFO_SD_FREE_FMT]         = "  SD Free: %s / %s",
    [STR_SYSINFO_OVERVIEW]            = "Overview",
    [STR_SYSINFO_HELP_1]              = "A: Open category list.",
    [STR_SYSINFO_HELP_2]              = "UP/DOWN: Select category.",
    [STR_SYSINFO_HELP_3]              = "B: Back to main menu.",
    [STR_SYSINFO_GAMES_HDR]           = "GAMES",
    [STR_SYSINFO_UPDATES_HDR]         = "UPDATES",
    [STR_SYSINFO_DLC_HDR]             = "DLC",
    [STR_SYSINFO_HDR_COUNT_FMT]       = "%s (%d)",
    [STR_SYSINFO_A_DETAILS]           = "A: Details & actions",

    [STR_SETTINGS_HEADER]             = "SETTINGS",
    [STR_SETTINGS_FORCE_BACKUP]       = "Force Backup:",
    [STR_SETTINGS_SKIP_UNINSTALL]     = "Skip Uninstall Confirm:",
    [STR_SETTINGS_FORCE_RESTORE]      = "Force Restore:",
    [STR_SETTINGS_SKIP_INSTALL]       = "Skip Install Confirm:",
    [STR_SETTINGS_BACKUP_FOLDER]      = "Backup Folder:",
    [STR_SETTINGS_LANGUAGE]           = "Language:",
    [STR_SETTINGS_ON]                 = "ON",
    [STR_SETTINGS_OFF]                = "OFF",
    [STR_SETTINGS_SEE_BOTTOM]         = "<see bottom>",
    [STR_SETTINGS_DESC_HEADER]        = "Description",
    [STR_SETTINGS_DESC_FORCEBK_1]     = "Auto-backup saves before",
    [STR_SETTINGS_DESC_FORCEBK_2]     = "every uninstall (no prompt).",
    [STR_SETTINGS_DESC_FORCEBK_3]     = "Recommended: ON for safety.",
    [STR_SETTINGS_DESC_SKIPUNINST_1]  = "Skip the uninstall prompt.",
    [STR_SETTINGS_DESC_SKIPUNINST_2]  = "Title deletes immediately on X.",
    [STR_SETTINGS_DESC_SKIPUNINST_3]  = "Recommended: OFF (always confirm).",
    [STR_SETTINGS_DESC_FORCERESTORE_1]= "Auto-restore save data",
    [STR_SETTINGS_DESC_FORCERESTORE_2]= "after every successful CIA install.",
    [STR_SETTINGS_DESC_FORCERESTORE_3]= "Use only with up-to-date backups.",
    [STR_SETTINGS_DESC_SKIPINSTALL_1] = "Skip the install prompt.",
    [STR_SETTINGS_DESC_SKIPINSTALL_2] = "CIA installs immediately on A.",
    [STR_SETTINGS_DESC_SKIPINSTALL_3] = "Recommended: OFF (always confirm).",
    [STR_SETTINGS_DESC_BACKUPFOLDER_1]= "Folder for save backups.",
    [STR_SETTINGS_DESC_BACKUPFOLDER_2]= "Use Left/Right or L/R to cycle",
    [STR_SETTINGS_DESC_BACKUPFOLDER_3]= "through 5 available destinations.",
    [STR_SETTINGS_DESC_LANGUAGE_1]    = "App display language.",
    [STR_SETTINGS_DESC_LANGUAGE_2]    = "Use Left/Right or L/R to switch",
    [STR_SETTINGS_DESC_LANGUAGE_3]    = "between English and Italian.",
    [STR_SETTINGS_CURRENT_PATH]       = "Current path:",
    [STR_SETTINGS_SAVED_REALTIME]     = "Changes saved in real time.",

    [STR_DETAIL_RELATED]              = "Related:",
    [STR_DETAIL_RELATED_UPD_FMT]      = "  [Upd] %.32s",
    [STR_DETAIL_RELATED_DLC_FMT]      = "  [DLC] %.32s",
    [STR_DETAIL_ACTION_BACKUP]        = "[A] Backup Save Data",
    [STR_DETAIL_ACTION_RESTORE]       = "[Y] Restore Save Data",
    [STR_DETAIL_ACTION_DELETE]        = "[X] Delete Title (+ related)",
    [STR_DETAIL_FOOTER_NAV]           = "Up/Down: Nav  A: Execute  B: Back",
    [STR_DETAIL_ACTION_HEADER]        = "Action",
    [STR_DETAIL_DESC_BACKUP_1]        = "Save the title data",
    [STR_DETAIL_DESC_BACKUP_2]        = "to the configured backup folder.",
    [STR_DETAIL_DESC_RESTORE_1]       = "Restore data from backup",
    [STR_DETAIL_DESC_RESTORE_2]       = "previously created.",
    [STR_DETAIL_DESC_DELETE_1]        = "Delete the title from the system",
    [STR_DETAIL_DESC_DELETE_2]        = "including DLC, Updates and data.",
    [STR_DETAIL_CONFIRM_ACTION]       = "A: confirm action",

    [STR_HELP_TITLE_MAINMENU]         = "Main Menu Help",
    [STR_HELP_TITLE_INSTALL]          = "Install CIA Help",
    [STR_HELP_TITLE_BACKUP]           = "Backup Saves Help",
    [STR_HELP_TITLE_UNINSTALL]        = "Uninstall Help",
    [STR_HELP_TITLE_SYSINFO]          = "System Info Help",
    [STR_HELP_TITLE_SETTINGS]         = "Settings Help",
    [STR_HELP_KEY_UPDOWN]             = "Up/Down",
    [STR_HELP_KEY_LEFTRIGHT]          = "Left/Right",
    [STR_HELP_KEY_A_LR_LEFTRIGHT]     = "A/Left/Right/L/R",
    [STR_HELP_KEY_B_START]            = "B/START",
    [STR_HELP_DESC_NAV_MENU]          = "Navigate menu",
    [STR_HELP_DESC_ENTER_SCREEN]      = "Enter screen",
    [STR_HELP_DESC_EXIT_APP]          = "Exit app",
    [STR_HELP_DESC_ENTER_INSTALL]     = "Enter folder / Install CIA",
    [STR_HELP_DESC_INSTALL_ALL]       = "Install all in folder",
    [STR_HELP_DESC_GO_UP]             = "Go up one level",
    [STR_HELP_DESC_PAGE_JUMP]         = "Page jump",
    [STR_HELP_DESC_BACK_MENU]         = "Back to menu",
    [STR_HELP_DESC_SELECT_TITLE]      = "Select title",
    [STR_HELP_DESC_BACKUP_SELECTED]   = "Backup selected",
    [STR_HELP_DESC_BACKUP_ALL]        = "Backup all titles",
    [STR_HELP_DESC_SORT]              = "Sort",
    [STR_HELP_DESC_TOGGLE_SELECTION]  = "Toggle selection",
    [STR_HELP_DESC_START_UNINSTALL]   = "Start uninstall flow",
    [STR_HELP_DESC_CYCLE_SORT]        = "Cycle sort",
    [STR_HELP_DESC_CYCLE_FILTER]      = "Cycle filter",
    [STR_HELP_DESC_NAVIGATE]          = "Navigate",
    [STR_HELP_DESC_OPEN_CATEGORY]     = "Open category / details",
    [STR_HELP_DESC_SORT_CATEGORY]     = "Sort (in category)",
    [STR_HELP_DESC_BACK]              = "Back",
    [STR_HELP_DESC_CHANGE_VALUE]      = "Change value",
    [STR_HELP_DESC_SAVE_BACK]         = "Save and back",
    [STR_HELP_HINT_MAINMENU]          = "A: Confirm selection",
    [STR_HELP_HINT_INSTALL]           = "Title details shown on bottom screen",
    [STR_HELP_HINT_BACKUP]            = "Title details + backup status below",
    [STR_HELP_HINT_UNINSTALL]         = "Selected titles shown on bottom screen",
    [STR_HELP_HINT_SYSINFO]           = "Title details and actions on bottom screen",
    [STR_HELP_HINT_SETTINGS]          = "Setting descriptions shown on bottom screen",

    [STR_DLG_NO_CIA_IN_FOLDER]        = "  No CIA files in this folder.",
    [STR_DLG_INSTALL_N_CIA_FMT]       = "  Install %d CIA files?",
    [STR_DLG_DEST_SD]                 = "  Destination: SD card",
    [STR_DLG_INSTALL_QUESTION]        = "  Install?",
    [STR_DLG_ID_FMT]                  = "  ID: %016llX",
    [STR_DLG_ID_NA]                   = "  ID: N/A",
    [STR_DLG_INSTALLATION_COMPLETE]   = "  Installation complete!",
    [STR_DLG_ERROR_INSTALLING]        = "  Error during installation.",
    [STR_DLG_CHECK_CIA_VALID]         = "  Check that the CIA file is valid.",
    [STR_DLG_SAVE_RESTORED_AUTO_1]    = "  Save data restored",
    [STR_DLG_SAVE_RESTORED_AUTO_2]    = "  automatically.",
    [STR_DLG_SAVE_RESTORED]           = "  Save data restored.",
    [STR_DLG_FOUND_BACKUP_TITLE]      = "  Found backup for this title.",
    [STR_DLG_RESTORE_QUESTION]        = "  Restore save data?",
    [STR_DLG_BATCH_INSTALL_DONE]      = "  Batch install completed.",
    [STR_DLG_INSTALLED_FAILED_FMT]    = "  Installed: %d   Failed: %d",

    [STR_DLG_NO_TITLE_SELECTED_SHORT] = "  No title selected.",
    [STR_DLG_SELECT_WITH_A]           = "  Select titles with A.",
    [STR_DLG_PRESS_A_CONTINUE]        = "  Press A to continue.",
    [STR_DLG_BACKUP_N_SELECTED_FMT]   = "  Backup %d selected titles?",
    [STR_DLG_BACKUP_ALL_N_FMT]        = "  Backup ALL titles (%d)?",
    [STR_DLG_MAY_TAKE_A_WHILE]        = "  This may take a while.",
    [STR_DLG_BACKUP_COMPLETED_FMT]    = "  Backup completed: %d ok, %d failed.",

    [STR_DLG_NO_TITLE_SELECTED_LONG]  = "  No title selected.",
    [STR_DLG_SELECT_AT_LEAST_ONE]     = "  Select at least one title with A.",
    [STR_DLG_FOUND_RELATED_FMT]       = "  Found %d related titles (DLC/Update).",
    [STR_DLG_INCLUDE_SKIP_CANCEL]     = "  A=Include  B=Skip  START=Cancel",
    [STR_DLG_BACKUP_SAVE_DATA_Q]      = "  Backup save data?",
    [STR_DLG_YES_NO_CANCEL]           = "  A=Yes   B=No   START=Cancel",
    [STR_DLG_USE_DEFAULT_CHOOSE]      = "  A=Use default   Y=Choose other",
    [STR_DLG_SELECT_BACKUP_FOLDER]    = "  Select backup folder:",
    [STR_DLG_UPDOWN_CONFIRM_CANCEL]   = "  Up/Down=Change   A=Confirm   B=Cancel",
    [STR_DLG_DELETE_N_TITLES_FMT]     = "  Delete %d titles?",
    [STR_DLG_BACKUP_TO_FMT]           = "  Backup to: %.36s",
    [STR_DLG_NO_BACKUP_PERIOD]        = "  No backup.",
    [STR_DLG_CONFIRM_CANCEL]          = "  A=Confirm   B=Cancel",
    [STR_DLG_N_BACKUPS_FAILED_FMT]    = "  %d backup(s) failed.",
    [STR_DLG_N_TITLES_NOT_DELETED_FMT]= "  %d title(s) NOT deleted.",
    [STR_DLG_SUCCESSFULLY_DELETED]    = " Successfully deleted:",
    [STR_DLG_ALL_DATA_REMOVED]        = "All data removed.",
    [STR_DLG_PRESS_A_CONTINUE_CAP]    = "Press A to continue...",
    [STR_DLG_FAILED_TO_DELETE]        = " Failed to delete:",
    [STR_DLG_TITLE_MAY_REMAIN]        = "Title may still be present.",

    [STR_DLG_BACKUP_COMPLETED_SIMPLE] = "  Backup completed.",
    [STR_DLG_BACKUP_FAILED_SIMPLE]    = "  Backup failed.",
    [STR_DLG_NO_BACKUP_AVAILABLE]     = "  No backup available.",
    [STR_DLG_RESTORE_ERROR]           = "  Restore error.",
};

static const char *stringsIT[STR_COUNT] = {
    [STR_FOOTER_BACK_EXIT_HELP]       = "B: Indietro  START: Esci  SEL: Aiuto",
    [STR_SELECTED_FMT]                = "Selezionati (%d)",
    [STR_AND_N_MORE_FMT]              = "...e altri %d",
    [STR_NO_BACKUP]                   = "Nessun backup",
    [STR_BACKUP_FMT]                  = "Backup: %s",
    [STR_UNKNOWN]                     = "Sconosciuto",
    [STR_TYPE_UPDATE]                 = "Agg.",
    [STR_TYPE_DLC]                    = "DLC",
    [STR_TYPE_GAME]                   = "Gioco",
    [STR_SORT_NAME]                   = "Nome",
    [STR_SORT_SIZE]                   = "Dim.",
    [STR_SORT_ID]                     = "ID",
    [STR_TITLE_DETAILS]               = "Dettagli Titolo",
    [STR_RELEASE_SELECT_RETURN]       = "Rilascia SELECT per tornare indietro.",
    [STR_A_CONTINUE]                  = "  A=Continua",
    [STR_A_OK]                        = "  A=OK",
    [STR_A_YES_B_NO]                  = "  A=Si    B=No",
    [STR_LOADING]                     = "Caricamento...",
    [STR_LOADING_TITLES]              = "Caricamento titoli...",
    [STR_DO_NOT_POWER_OFF]            = "Non spegnere la console.",

    [STR_APP_TITLE_FMT]               = "3DS Fast Uninstall  %s",
    [STR_MENU_INSTALL]                = "Installa CIA",
    [STR_MENU_BACKUP]                 = "Backup Salvataggi",
    [STR_MENU_UNINSTALL]              = "Disinstalla Titoli",
    [STR_MENU_SYSINFO]                = "Informazioni",
    [STR_MENU_SETTINGS]               = "Impostazioni",
    [STR_MENU_FOOTER_TOP]             = "START: Esci  SELECT: Aiuto",
    [STR_MENU_FOOTER_BOTTOM]          = "A: Seleziona  START: Esci  SEL: Aiuto",
    [STR_MENU_DESCRIPTION]            = "Descrizione",
    [STR_MENU_DESC_INSTALL_1]         = "Installa file .CIA dalla scheda SD.",
    [STR_MENU_DESC_INSTALL_2]         = "Supporta installazione singola e in batch.",
    [STR_MENU_DESC_BACKUP_1]          = "Backup dei salvataggi dei titoli installati.",
    [STR_MENU_DESC_BACKUP_2]          = "Backup di un titolo o dell'intera libreria.",
    [STR_MENU_DESC_UNINSTALL_1]       = "Disinstalla titoli con backup opzionale.",
    [STR_MENU_DESC_UNINSTALL_2]       = "Disinstallazione multipla col tasto X.",
    [STR_MENU_DESC_SYSINFO_1]         = "Info su giochi, aggiornamenti e DLC.",
    [STR_MENU_DESC_SYSINFO_2]         = "Include backup, ripristino ed eliminazione.",
    [STR_MENU_DESC_SETTINGS_1]        = "Configura le impostazioni dell'app.",

    [STR_UNINSTALL_HEADER]            = "Disinstalla",
    [STR_UNINSTALL_INFO_FMT]          = "T:%-3d Sel:%-3d Ord.:",
    [STR_FILTER_ALL]                  = "Tutti",
    [STR_FILTER_UPD]                  = "Agg",
    [STR_FILTER_DLC]                  = "DLC",
    [STR_NO_TITLES]                   = "Nessun titolo da mostrare.",

    [STR_INSTALL_HEADER]              = "Installa CIA",
    [STR_DIR_PREFIX_FMT]              = "[DIR] %s/",
    [STR_FILE_INFO]                   = "Info File",
    [STR_FILE_ID_FMT]                 = "ID: %016llX",
    [STR_FILE_ID_NA]                  = "ID: N/D",
    [STR_FILE_SIZE_FMT]               = "Dim.: %s",
    [STR_GO_TO_PARENT]                = "Vai alla cartella superiore",
    [STR_FOLDER_FMT]                  = "Cartella: %.30s",
    [STR_EMPTY_FOLDER]                = "Cartella vuota",
    [STR_TYPE_UPDATE_BADGE]           = "Tipo: Agg.    [^]",
    [STR_TYPE_DLC_BADGE]              = "Tipo: DLC     [+]",
    [STR_TYPE_GAME_LABEL]             = "Tipo: Gioco",

    [STR_BACKUP_HEADER_FMT]           = "Backup Salvataggi   Sel:%d",
    [STR_SORT_FMT]                    = "Ord.:%s",

    [STR_SYSINFO_HEADER]              = "INFORMAZIONI DI SISTEMA",
    [STR_SYSINFO_ROW_GAMES]           = "Giochi:",
    [STR_SYSINFO_ROW_UPDATES]         = "Aggiornamenti:",
    [STR_SYSINFO_ROW_DLC]             = "DLC:",
    [STR_SYSINFO_SD_FREE_FMT]         = "  SD Liberi: %s / %s",
    [STR_SYSINFO_OVERVIEW]            = "Panoramica",
    [STR_SYSINFO_HELP_1]              = "A: Apri elenco categorie.",
    [STR_SYSINFO_HELP_2]              = "SU/GIU: Seleziona categoria.",
    [STR_SYSINFO_HELP_3]              = "B: Torna al menu principale.",
    [STR_SYSINFO_GAMES_HDR]           = "GIOCHI",
    [STR_SYSINFO_UPDATES_HDR]         = "AGGIORNAMENTI",
    [STR_SYSINFO_DLC_HDR]             = "DLC",
    [STR_SYSINFO_HDR_COUNT_FMT]       = "%s (%d)",
    [STR_SYSINFO_A_DETAILS]           = "A: Dettagli e azioni",

    [STR_SETTINGS_HEADER]             = "IMPOSTAZIONI",
    [STR_SETTINGS_FORCE_BACKUP]       = "Backup forzato:",
    [STR_SETTINGS_SKIP_UNINSTALL]     = "Salta conf. disinst.:",
    [STR_SETTINGS_FORCE_RESTORE]      = "Ripristino forzato:",
    [STR_SETTINGS_SKIP_INSTALL]       = "Salta conf. install.:",
    [STR_SETTINGS_BACKUP_FOLDER]      = "Cartella backup:",
    [STR_SETTINGS_LANGUAGE]           = "Lingua:",
    [STR_SETTINGS_ON]                 = "ON",
    [STR_SETTINGS_OFF]                = "OFF",
    [STR_SETTINGS_SEE_BOTTOM]         = "<vedi sotto>",
    [STR_SETTINGS_DESC_HEADER]        = "Descrizione",
    [STR_SETTINGS_DESC_FORCEBK_1]     = "Backup automatico prima di",
    [STR_SETTINGS_DESC_FORCEBK_2]     = "ogni disinstallazione (nessun avviso).",
    [STR_SETTINGS_DESC_FORCEBK_3]     = "Consigliato: ON per sicurezza.",
    [STR_SETTINGS_DESC_SKIPUNINST_1]  = "Salta l'avviso di disinstallazione.",
    [STR_SETTINGS_DESC_SKIPUNINST_2]  = "Il titolo si elimina subito con X.",
    [STR_SETTINGS_DESC_SKIPUNINST_3]  = "Consigliato: OFF (conferma sempre).",
    [STR_SETTINGS_DESC_FORCERESTORE_1]= "Ripristina automaticamente il",
    [STR_SETTINGS_DESC_FORCERESTORE_2]= "salvataggio dopo ogni installazione CIA.",
    [STR_SETTINGS_DESC_FORCERESTORE_3]= "Usare solo con backup aggiornati.",
    [STR_SETTINGS_DESC_SKIPINSTALL_1] = "Salta l'avviso di installazione.",
    [STR_SETTINGS_DESC_SKIPINSTALL_2] = "Il CIA si installa subito con A.",
    [STR_SETTINGS_DESC_SKIPINSTALL_3] = "Consigliato: OFF (conferma sempre).",
    [STR_SETTINGS_DESC_BACKUPFOLDER_1]= "Cartella per i backup salvataggi.",
    [STR_SETTINGS_DESC_BACKUPFOLDER_2]= "Usa Sinistra/Destra o L/R per",
    [STR_SETTINGS_DESC_BACKUPFOLDER_3]= "scorrere le 5 destinazioni disponibili.",
    [STR_SETTINGS_DESC_LANGUAGE_1]    = "Lingua dell'interfaccia.",
    [STR_SETTINGS_DESC_LANGUAGE_2]    = "Usa Sinistra/Destra o L/R per passare",
    [STR_SETTINGS_DESC_LANGUAGE_3]    = "da Italiano a Inglese.",
    [STR_SETTINGS_CURRENT_PATH]       = "Percorso attuale:",
    [STR_SETTINGS_SAVED_REALTIME]     = "Modifiche salvate in tempo reale.",

    [STR_DETAIL_RELATED]              = "Correlati:",
    [STR_DETAIL_RELATED_UPD_FMT]      = "  [Agg] %.32s",
    [STR_DETAIL_RELATED_DLC_FMT]      = "  [DLC] %.32s",
    [STR_DETAIL_ACTION_BACKUP]        = "[A] Backup Salvataggio",
    [STR_DETAIL_ACTION_RESTORE]       = "[Y] Ripristina Salvataggio",
    [STR_DETAIL_ACTION_DELETE]        = "[X] Elimina Titolo (+ correlati)",
    [STR_DETAIL_FOOTER_NAV]           = "Su/Giu: Naviga  A: Esegui  B: Indietro",
    [STR_DETAIL_ACTION_HEADER]        = "Azione",
    [STR_DETAIL_DESC_BACKUP_1]        = "Salva i dati del titolo nella",
    [STR_DETAIL_DESC_BACKUP_2]        = "cartella di backup configurata.",
    [STR_DETAIL_DESC_RESTORE_1]       = "Ripristina i dati dall'ultimo",
    [STR_DETAIL_DESC_RESTORE_2]       = "backup creato.",
    [STR_DETAIL_DESC_DELETE_1]        = "Elimina il titolo dal sistema,",
    [STR_DETAIL_DESC_DELETE_2]        = "inclusi DLC, Aggiornamenti e dati.",
    [STR_DETAIL_CONFIRM_ACTION]       = "A: conferma azione",

    [STR_HELP_TITLE_MAINMENU]         = "Aiuto Menu Principale",
    [STR_HELP_TITLE_INSTALL]          = "Aiuto Installa CIA",
    [STR_HELP_TITLE_BACKUP]           = "Aiuto Backup Salvataggi",
    [STR_HELP_TITLE_UNINSTALL]        = "Aiuto Disinstalla",
    [STR_HELP_TITLE_SYSINFO]          = "Aiuto Informazioni",
    [STR_HELP_TITLE_SETTINGS]         = "Aiuto Impostazioni",
    [STR_HELP_KEY_UPDOWN]             = "Su/Giu",
    [STR_HELP_KEY_LEFTRIGHT]          = "Sinistra/Destra",
    [STR_HELP_KEY_A_LR_LEFTRIGHT]     = "A/Sin/Des/L/R",
    [STR_HELP_KEY_B_START]            = "B/START",
    [STR_HELP_DESC_NAV_MENU]          = "Naviga il menu",
    [STR_HELP_DESC_ENTER_SCREEN]      = "Apri schermata",
    [STR_HELP_DESC_EXIT_APP]          = "Esci dall'app",
    [STR_HELP_DESC_ENTER_INSTALL]     = "Apri cartella / Installa CIA",
    [STR_HELP_DESC_INSTALL_ALL]       = "Installa tutti nella cartella",
    [STR_HELP_DESC_GO_UP]             = "Sali di un livello",
    [STR_HELP_DESC_PAGE_JUMP]         = "Salto pagina",
    [STR_HELP_DESC_BACK_MENU]         = "Torna al menu",
    [STR_HELP_DESC_SELECT_TITLE]      = "Seleziona titolo",
    [STR_HELP_DESC_BACKUP_SELECTED]   = "Backup selezionati",
    [STR_HELP_DESC_BACKUP_ALL]        = "Backup di tutti i titoli",
    [STR_HELP_DESC_SORT]              = "Ordina",
    [STR_HELP_DESC_TOGGLE_SELECTION]  = "Attiva/disattiva selezione",
    [STR_HELP_DESC_START_UNINSTALL]   = "Avvia disinstallazione",
    [STR_HELP_DESC_CYCLE_SORT]        = "Cambia ordinamento",
    [STR_HELP_DESC_CYCLE_FILTER]      = "Cambia filtro",
    [STR_HELP_DESC_NAVIGATE]          = "Naviga",
    [STR_HELP_DESC_OPEN_CATEGORY]     = "Apri categoria / dettagli",
    [STR_HELP_DESC_SORT_CATEGORY]     = "Ordina (nella categoria)",
    [STR_HELP_DESC_BACK]              = "Indietro",
    [STR_HELP_DESC_CHANGE_VALUE]      = "Cambia valore",
    [STR_HELP_DESC_SAVE_BACK]         = "Salva e torna indietro",
    [STR_HELP_HINT_MAINMENU]          = "A: Conferma selezione",
    [STR_HELP_HINT_INSTALL]           = "Dettagli titolo sullo schermo inferiore",
    [STR_HELP_HINT_BACKUP]            = "Dettagli e stato backup sotto",
    [STR_HELP_HINT_UNINSTALL]         = "Titoli selezionati sullo schermo inferiore",
    [STR_HELP_HINT_SYSINFO]           = "Dettagli e azioni sullo schermo inferiore",
    [STR_HELP_HINT_SETTINGS]          = "Descrizioni sullo schermo inferiore",

    [STR_DLG_NO_CIA_IN_FOLDER]        = "  Nessun file CIA in questa cartella.",
    [STR_DLG_INSTALL_N_CIA_FMT]       = "  Installare %d file CIA?",
    [STR_DLG_DEST_SD]                 = "  Destinazione: scheda SD",
    [STR_DLG_INSTALL_QUESTION]        = "  Installare?",
    [STR_DLG_ID_FMT]                  = "  ID: %016llX",
    [STR_DLG_ID_NA]                   = "  ID: N/D",
    [STR_DLG_INSTALLATION_COMPLETE]   = "  Installazione completata!",
    [STR_DLG_ERROR_INSTALLING]        = "  Errore durante l'installazione.",
    [STR_DLG_CHECK_CIA_VALID]         = "  Verifica che il file CIA sia valido.",
    [STR_DLG_SAVE_RESTORED_AUTO_1]    = "  Salvataggio ripristinato",
    [STR_DLG_SAVE_RESTORED_AUTO_2]    = "  automaticamente.",
    [STR_DLG_SAVE_RESTORED]           = "  Salvataggio ripristinato.",
    [STR_DLG_FOUND_BACKUP_TITLE]      = "  Trovato un backup per questo titolo.",
    [STR_DLG_RESTORE_QUESTION]        = "  Ripristinare il salvataggio?",
    [STR_DLG_BATCH_INSTALL_DONE]      = "  Installazione batch completata.",
    [STR_DLG_INSTALLED_FAILED_FMT]    = "  Installati: %d   Falliti: %d",

    [STR_DLG_NO_TITLE_SELECTED_SHORT] = "  Nessun titolo selezionato.",
    [STR_DLG_SELECT_WITH_A]           = "  Seleziona i titoli con A.",
    [STR_DLG_PRESS_A_CONTINUE]        = "  Premi A per continuare.",
    [STR_DLG_BACKUP_N_SELECTED_FMT]   = "  Backup di %d titoli selezionati?",
    [STR_DLG_BACKUP_ALL_N_FMT]        = "  Backup di TUTTI i titoli (%d)?",
    [STR_DLG_MAY_TAKE_A_WHILE]        = "  Potrebbe richiedere tempo.",
    [STR_DLG_BACKUP_COMPLETED_FMT]    = "  Backup completato: %d ok, %d falliti.",

    [STR_DLG_NO_TITLE_SELECTED_LONG]  = "  Nessun titolo selezionato.",
    [STR_DLG_SELECT_AT_LEAST_ONE]     = "  Seleziona almeno un titolo con A.",
    [STR_DLG_FOUND_RELATED_FMT]       = "  Trovati %d titoli correlati (DLC/Agg.).",
    [STR_DLG_INCLUDE_SKIP_CANCEL]     = "  A=Includi  B=Salta  START=Annulla",
    [STR_DLG_BACKUP_SAVE_DATA_Q]      = "  Eseguire il backup dei salvataggi?",
    [STR_DLG_YES_NO_CANCEL]           = "  A=Si   B=No   START=Annulla",
    [STR_DLG_USE_DEFAULT_CHOOSE]      = "  A=Predefinito   Y=Scegli altro",
    [STR_DLG_SELECT_BACKUP_FOLDER]    = "  Seleziona cartella di backup:",
    [STR_DLG_UPDOWN_CONFIRM_CANCEL]   = "  Su/Giu=Cambia   A=Conferma   B=Annulla",
    [STR_DLG_DELETE_N_TITLES_FMT]     = "  Eliminare %d titoli?",
    [STR_DLG_BACKUP_TO_FMT]           = "  Backup in: %.36s",
    [STR_DLG_NO_BACKUP_PERIOD]        = "  Nessun backup.",
    [STR_DLG_CONFIRM_CANCEL]          = "  A=Conferma   B=Annulla",
    [STR_DLG_N_BACKUPS_FAILED_FMT]    = "  %d backup falliti.",
    [STR_DLG_N_TITLES_NOT_DELETED_FMT]= "  %d titoli NON eliminati.",
    [STR_DLG_SUCCESSFULLY_DELETED]    = " Eliminato con successo:",
    [STR_DLG_ALL_DATA_REMOVED]        = "Tutti i dati rimossi.",
    [STR_DLG_PRESS_A_CONTINUE_CAP]    = "Premi A per continuare...",
    [STR_DLG_FAILED_TO_DELETE]        = " Eliminazione fallita:",
    [STR_DLG_TITLE_MAY_REMAIN]        = "Il titolo potrebbe essere ancora presente.",

    [STR_DLG_BACKUP_COMPLETED_SIMPLE] = "  Backup completato.",
    [STR_DLG_BACKUP_FAILED_SIMPLE]    = "  Backup fallito.",
    [STR_DLG_NO_BACKUP_AVAILABLE]     = "  Nessun backup disponibile.",
    [STR_DLG_RESTORE_ERROR]           = "  Errore di ripristino.",
};

static const char **const tables[LANG_COUNT] = { stringsEN, stringsIT };

const char *T(StringID id) {
    if (id < 0 || id >= STR_COUNT) return "";
    Language lang = config.language;
    if (lang < 0 || lang >= LANG_COUNT) lang = LANG_EN;
    const char *s = tables[lang][id];
    if (!s) s = tables[LANG_EN][id];
    return s ? s : "";
}

Language detectSystemLanguage(void) {
    u8 sysLang = CFG_LANGUAGE_EN;
    CFGU_GetSystemLanguage(&sysLang);
    return (sysLang == CFG_LANGUAGE_IT) ? LANG_IT : LANG_EN;
}
